import { mkdirSync, copyFileSync, writeFileSync } from 'node:fs'
mkdirSync('lib/types', { recursive: true })
mkdirSync('lib/types/client', { recursive: true })
mkdirSync('client', { recursive: true })
copyFileSync('src/index.js', 'lib/index.js')
copyFileSync('src/store.js', 'lib/store.js')
copyFileSync('src/skill.js', 'lib/skill.js')
copyFileSync('src/routes.js', 'lib/routes.js')
copyFileSync('src/http.js', 'lib/http.js')
copyFileSync('client/client.js', 'lib/client.js')
writeFileSync('lib/types/index.d.ts', 'export const name: string; export const inject: string[]; export function apply(ctx: any, config?: any): void;\n')
writeFileSync('lib/types/store.d.ts', 'export class WorkspaceStore { constructor(filePath: string); listWorld(worldId?: string): any; get(id: string): any; search(query?: any): any; overview(input?: any): any; resume(input?: any): any; getNode(id: string, includeDeleted?: boolean): any; getRetrievableNode(id: string): any; upsertNode(input: any): any; addToWorld(input?: any): any; removeFromWorld(input?: any): any; deleteNode(id: string): any; upsertEdge(input: any): any; deleteEdge(id: string): any; archiveSession(input: any): any; context(input?: any): any; }\nexport class RevisionConflictError extends Error { code: string; currentRevision: number; }\n')
writeFileSync('lib/types/client/index.d.ts', 'export const name: string; export const inject: string[]; export function apply(ctx: any): void;\n')
console.log('built dsh-hako-workspace')
